// Board registry for this fork: one board — the Lily58 (inogai/zmk-config ZMK keymap).
// The board file is generated by zmk-config/trainer/tools/gen_board.py from
// config/lily58.keymap (BASE + NAV layers) — re-run it after keymap changes.

import { board as lily58 } from './lily58.js';

export const BOARDS = [lily58];

export const DEFAULT_BOARD_ID = 'lily58';

export function listBoards() {
  return BOARDS;
}

export function listPlayableBoards() {
  return BOARDS.filter((b) => !b.comingSoon);
}

export function getBoard(id) {
  const playable = listPlayableBoards();
  return playable.find((b) => b.id === id)
    ?? playable.find((b) => b.id === DEFAULT_BOARD_ID)
    ?? playable[0];
}

export function boardLabel(board) {
  if (!board) return '';
  return `${board.name} · ${board.formFactor}`;
}

export function boardFullLabel(board) {
  if (!board) return '';
  return `${board.productName}, ${board.formFactor}`;
}
