// Generated by zmk-config/trainer/tools/gen_board.py — DO NOT EDIT BY HAND.
// Board: Lily58 (inogai/zmk-config) · slot 0 = BASE, slot 1 = NAV (hold comma).
import { createLayout } from './buildLayout.js';

const XX = null;

const LEFT = [
  [
    ["L00", "`", null, null],
    ["L01", "1", null, null],
    ["L02", "2", null, null],
    ["L03", "3", null, null],
    ["L04", "4", null, null],
    ["L05", "5", null, null],
  ],
  [
    ["L10", "Tab", null, null],
    ["L11", "Q", null, null],
    ["L12", "W", null, null],
    ["L13", "E", null, null],
    ["L14", "R", null, null],
    ["L15", "T", null, null],
  ],
  [
    ["L20", "Shift", null, null],
    ["L21", "A", null, null],
    ["L22", "S", null, null],
    ["L23", "D", null, null],
    ["L24", "F", null, null],
    ["L25", "G", null, null],
  ],
  [
    ["L30", "Ctrl", null, null],
    ["L31", ",", null, null],
    ["L32", "Z", null, null],
    ["L33", "X", null, null],
    ["L34", "C", null, null],
    ["L35", "V", null, null],
  ],
  [
    ["L40", "Alt", null, null],
    ["L41", "Esc", null, null],
    ["L42", "Space", null, null],
  ],
];

const RIGHT = [
  [
    ["R00", "6", null, null],
    ["R01", "7", null, null],
    ["R02", "8", null, null],
    ["R03", "9", null, null],
    ["R04", "0", null, null],
    ["R05", "-", null, null],
  ],
  [
    ["R10", "Y", null, null],
    ["R11", "U", null, null],
    ["R12", "I", null, null],
    ["R13", "O", null, null],
    ["R14", "P", null, null],
    ["R15", "=", null, null],
  ],
  [
    ["R20", "H", "←", null],
    ["R21", "J", "↓", null],
    ["R22", "K", "↑", null],
    ["R23", "L", "→", null],
    ["R24", ";", null, null],
  ],
  [
    ["R30", "B", "⇤", null],
    ["R31", "N", "⇥", null],
    ["R32", "M", "⇑", null],
    ["R33", ".", "⇓", null],
    ["R34", "/", null, null],
  ],
  [
    ["R40", "Ret", "Ret", null],
    ["R41", "Bspc", "Bspc", null],
    ["R42", "Del", "Del", null],
  ],
];

const layout = createLayout({
  left: LEFT,
  right: RIGHT,
  layerHold: {"1": "L31"},
  shiftKeys: ["L20"],
  spaceKeyId: "L42",
  shiftedL0: {
    ':': ';', '<': ',', '>': '.', '?': '/', '_': '-',
    '!': '1', '@': '2', '#': '3', '$': '4', '%': '5', '^': '6', '&': '7', '*': '8',
    '(': '9', ')': '0',
  },
});

/** @type {ReturnType<typeof createLayout> & { id: string, name: string, productName: string, formFactor: string, description: string, geometry: string, vilPath: null, comingSoon: boolean, homeIds: string[], positions: Record<string, {x:number,y:number,w?:number,h?:number,r?:number}> }} */
export const board = {
  id: 'lily58',
  name: 'Lily58',
  productName: 'Lily58 (inogai/zmk-config, Miryoku-style)',
  formFactor: '5-row split · 58 keys',
  description: 'Lily58 with shifted bottom row (ZXCV/B/comma) and hold-comma NAV layer.',
  geometry: 'lily58',
  vilPath: null,
  comingSoon: false,
  homeIds: ["L21", "L22", "L23", "L24", "R20", "R21", "R22", "R23"],
  positions: {"L00": {"x": 0, "y": 0.05}, "L01": {"x": 1, "y": 0.15}, "L02": {"x": 2, "y": 0.25}, "L03": {"x": 3, "y": 0.35}, "L04": {"x": 4, "y": 0.35}, "L05": {"x": 5, "y": 0.45}, "L10": {"x": 0, "y": 1.05}, "L11": {"x": 1, "y": 1.15}, "L12": {"x": 2, "y": 1.25}, "L13": {"x": 3, "y": 1.35}, "L14": {"x": 4, "y": 1.35}, "L15": {"x": 5, "y": 1.45}, "L20": {"x": 0, "y": 2.05}, "L21": {"x": 1, "y": 2.15}, "L22": {"x": 2, "y": 2.25}, "L23": {"x": 3, "y": 2.35}, "L24": {"x": 4, "y": 2.35}, "L25": {"x": 5, "y": 2.45}, "L30": {"x": 0, "y": 3.05}, "L31": {"x": 1, "y": 3.15}, "L32": {"x": 2, "y": 3.25}, "L33": {"x": 3, "y": 3.35}, "L34": {"x": 4, "y": 3.35}, "L35": {"x": 5, "y": 3.45}, "R00": {"x": 0, "y": 0.45}, "R01": {"x": 1, "y": 0.35}, "R02": {"x": 2, "y": 0.35}, "R03": {"x": 3, "y": 0.25}, "R04": {"x": 4, "y": 0.15}, "R05": {"x": 5, "y": 0.05}, "R10": {"x": 0, "y": 1.45}, "R11": {"x": 1, "y": 1.35}, "R12": {"x": 2, "y": 1.35}, "R13": {"x": 3, "y": 1.25}, "R14": {"x": 4, "y": 1.15}, "R15": {"x": 5, "y": 1.05}, "R20": {"x": 0, "y": 2.45}, "R21": {"x": 1, "y": 2.35}, "R22": {"x": 2, "y": 2.35}, "R23": {"x": 3, "y": 2.25}, "R24": {"x": 4, "y": 2.15}, "R30": {"x": 0, "y": 3.45}, "R31": {"x": 1, "y": 3.35}, "R32": {"x": 2, "y": 3.35}, "R33": {"x": 3, "y": 3.25}, "R34": {"x": 4, "y": 3.15}, "L40": {"x": 2.2, "y": 4.25}, "L41": {"x": 3.35, "y": 4.45}, "L42": {"x": 4.5, "y": 4.05, "w": 1, "h": 1.5}, "R40": {"x": 3.0, "y": 4.05, "w": 1, "h": 1.5}, "R41": {"x": 1.85, "y": 4.25}, "R42": {"x": 0.7, "y": 4.4}},
  ...layout,
};

export default board;
