// Supplemental pools for bigrams / hold / pulse drills.
export const EXTRA_POOLS = {
  bigrams: ["th","he","in","er","an","re","on","at","en","nd","ti","es","or","te","of","ed","is","it","al","ar","st","to","nt","ng","se","ha","as","ou","io","le","ve","co","me","de","hi","ri","ro","ic","ne","ea","ra","ce","li","ch","ll","be","ma","si","om","ur","ca","el","la","ns","di","fo","ho","pe","ec","pr","the","and","ing","ion","ent","for","her","ter","hat","tha","ere","ate","his","con","res","ver","all","ons","nce","men","ith","ted","ers","pro","thi","wit","are","ess","not","ive","was","ect","rea","com","eve","per","int","est","sta","cti","ica","ist","ear","own","one","our","out","use","how","man","new","now","way","may","say","she","two","who","oil","sit","set","run","let","put","end","why","try","ask","th th","he he","in in","er er","an an","the the","and and","ing ing","ion ion","ent ent","that","with","have","this","will","your","from","they","been","call","each","which","their","said","there","about","would","make","like","time","very","when","come","here","just","into","year","over"],
  'hold-drill': ["←←", "→→", "↑↑", "↓↓", "←→", "→←", "↑↓", "↓↑", "←↓↑→", "→↑↓←", "←←→→", "↑↑↓↓", "←→←→", "↑↓↑↓", "←←←", "→→→", "↑↑↑", "↓↓↓", "←↓←↓", "→↑→↑", "↑→↑→", "↓←↓←", "←↑←↑", "→↓→↓", "↑←↑←", "↓→↓→", "←→↑↓", "→←↓↑", "↑↓←→", "↓↑→←", "←↓→↑", "→↑←↓", "↑→↓←", "↓←↑→", "←←↓↓", "→→↑↑", "↑↑←←", "↓↓→→", "←→→←", "↑↓↓↑", "→←←→", "↓↑↑↓", "←↑→↓←↑→↓", "→↓←↑→↓←↑", "↑→↓←↑→↓←", "↓←↑→↓←↑→", "←←↑↑→→↓↓", "→→↓↓←←↑↑", "↑↑→→↓↓←←", "↓↓←←↑↑→→", "←↓↑→←↓↑→", "→↑↓←→↑↓←", "↑←↓→↑←↓→", "↓→↑←↓→↑←"],
  'pulse-drill': ["a1","b2","c3","x9","y0","n1","m2","a1b","x2y","a=1","b=2","x=3","n=0","i=1","a[0]","b[1]","x[2]","a1a","b2b","1a1","2b2","x!","y!","ok!","go!","a$","b$","#1","#2","@a","@b","a&b","x*y","a-b","x=y","a_b","c|d","~a","a+b","[a]","{x}","`a`","a\\b","v1","v2","v1.0","v2.1","a1 a2","x9 y0","n=1;","i=0;","a[1]=2","x!=y","a&1","b|2","$5","10%","#9","@x","let x=1","var n=2","id=7","a+1","b-2","c*3","d/4","x^2","n%2","a_1","b-2","c.3","hi!","no!","yes!","ok.","a,b","x.y","1st","2nd","3rd","q1","q2","fy24","v3.14"],
};

// Drop glyphs absent from Eyelash BASE/NAV/SYM tutor slots (= and backslash are Num-hold).
for (const [name, items] of Object.entries(EXTRA_POOLS)) {
  EXTRA_POOLS[name] = items.filter((item) => !/[=\\]/.test(item));
}
